SET DB_CLOSE_DELAY -1;

CREATE USER IF NOT EXISTS "SA" SALT '169404be7b6898d3' HASH '8662fbe8c213e9e208b2b31ff973f4f90b3121e3d5c714fb59ed950d66753ea7' ADMIN;

CREATE SEQUENCE "PUBLIC"."LICENCE_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."MOVIE_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."SCREENING_SEQ" START WITH 1 RESTART WITH 1551 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."SEAT_SEQ" START WITH 1 RESTART WITH 151 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."THEATER_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;
CREATE SEQUENCE "PUBLIC"."TICKET_SEQ" START WITH 1 INCREMENT BY 50;

CREATE CACHED TABLE "PUBLIC"."LICENCE"(
    "END_TIME" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "LICENCE_ID" BIGINT NOT NULL,
    "MOVIE_ID" BIGINT NOT NULL,
    "START_TIME" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "THEATER_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."LICENCE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("LICENCE_ID");

CREATE CACHED TABLE "PUBLIC"."MOVIE"(
    "MOVIE_ID" BIGINT NOT NULL,
    "TITLE" CHARACTER VARYING(256) NOT NULL
);
ALTER TABLE "PUBLIC"."MOVIE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_46" PRIMARY KEY("MOVIE_ID");

CREATE CACHED TABLE "PUBLIC"."SCREENING"(
    "END_TIME" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "MOVIE_ID" BIGINT NOT NULL,
    "SCREENING_ID" BIGINT NOT NULL,
    "START_TIME" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "THEATER_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."SCREENING" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("SCREENING_ID");

CREATE CACHED TABLE "PUBLIC"."SEAT"(
    "SEAT_ID" BIGINT NOT NULL,
    "THEATER_ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(256) NOT NULL
);
ALTER TABLE "PUBLIC"."SEAT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("SEAT_ID");

CREATE CACHED TABLE "PUBLIC"."THEATER"(
    "THEATER_ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(256) NOT NULL
);
ALTER TABLE "PUBLIC"."THEATER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_DA" PRIMARY KEY("THEATER_ID");

CREATE CACHED TABLE "PUBLIC"."TICKET"(
    "SCREENING_ID" BIGINT NOT NULL,
    "SEAT_ID" BIGINT NOT NULL,
    "TICKET_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."TICKET" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("TICKET_ID");

ALTER TABLE "PUBLIC"."TICKET" ADD CONSTRAINT "PUBLIC"."UNIQUESCREENINGANDSEAT" UNIQUE("SCREENING_ID", "SEAT_ID");
ALTER TABLE "PUBLIC"."MOVIE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" UNIQUE("TITLE");
ALTER TABLE "PUBLIC"."SEAT" ADD CONSTRAINT "PUBLIC"."UKEUC84W5FDLNH4T3MWR028T4EY" UNIQUE("THEATER_ID", "NAME");
ALTER TABLE "PUBLIC"."THEATER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" UNIQUE("NAME");
ALTER TABLE "PUBLIC"."LICENCE" ADD CONSTRAINT "PUBLIC"."FK4TBJ15CC4N5CV37OY2WMWUH2F" FOREIGN KEY("MOVIE_ID") REFERENCES "PUBLIC"."MOVIE"("MOVIE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."SEAT" ADD CONSTRAINT "PUBLIC"."FKGIK5885QSFF01SXE7V3KQJRHX" FOREIGN KEY("THEATER_ID") REFERENCES "PUBLIC"."THEATER"("THEATER_ID") NOCHECK;
ALTER TABLE "PUBLIC"."SCREENING" ADD CONSTRAINT "PUBLIC"."FKFP7SH76XC9M508STLLSPCHNP9" FOREIGN KEY("MOVIE_ID") REFERENCES "PUBLIC"."MOVIE"("MOVIE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."LICENCE" ADD CONSTRAINT "PUBLIC"."FK9NUBCGWH5S19RXXUV54FOWPDL" FOREIGN KEY("THEATER_ID") REFERENCES "PUBLIC"."THEATER"("THEATER_ID") NOCHECK;
ALTER TABLE "PUBLIC"."SCREENING" ADD CONSTRAINT "PUBLIC"."FKCAMYGVCXV5AYWCMJOGP6UAYRE" FOREIGN KEY("THEATER_ID") REFERENCES "PUBLIC"."THEATER"("THEATER_ID") NOCHECK;
ALTER TABLE "PUBLIC"."TICKET" ADD CONSTRAINT "PUBLIC"."FKQAHAO9A85DRT47IKJP0B8SYVH" FOREIGN KEY("SEAT_ID") REFERENCES "PUBLIC"."SEAT"("SEAT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."TICKET" ADD CONSTRAINT "PUBLIC"."FKSLSBFJFVSW5V43W11JM31X0C6" FOREIGN KEY("SCREENING_ID") REFERENCES "PUBLIC"."SCREENING"("SCREENING_ID") NOCHECK;
